### ISSUE TITLE
How hard it would be to port entire inventory system to cpp?

### ISSUE THREAD

**Issue by KoxaKoxama** [expressobits/inventory-system-cpp#1]

**Comment by scriptsengineer** [comment]
This is not ready, the idea that before version 1.0.0 everything that is in the inventory system core would be ported to CPP, and would be included in the addon as a gdextension. However, until the end of the development of 1.0.0, I will use gdextension because it is faster to interact and make changes.
When this version arrives, it will obviously break compatibility with projects that use prior to 1.0.0, I intend to have a converter that moves the Item from gdscript to use the cpp node.

Before that, what needs to be done:
End interaction system
Inventories with items allocated with grids
Cool bugs

**Comment by scriptsengineer** [comment]
> It would be cool to completely port the entire inventory system to GDExtension, not just core. And please **don't mix it with GDScript** version, keep them as separate projects, there is no need for partial GDExtension implementation in GDScript version that already works great. On the other hand having a fully working C++ version would provide an amazing starting point for those who want to go full GDExtension way!

I have some updates:
1 - I have already started this work, I have ported all resources and inventory nodes, there are other core nodes missing. However, I ran into a problem that I imagine would be serious for someone who wants to extend its functionality, when a script is written in C++ it is not possible to use the override feature, I had the idea that the developer could expand its functionality, just like what happens with Slot. gd and CategorizedSlot.gd

2 - I'm carrying it out little by little, the idea is that at some point it will go beyond the core.

3- The C++ module would be independent of gdscript, that is, it could only be used if necessary.
